py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9
  script:
  - pip install tox
  - tox -e py39

py310:
  image: python:3.10
  script:
  - pip install tox
  - tox -e docs,format,mypy,py310,pep8,package

openapi-spec:
  image: python:3.10
  script:
  - pip install openapi-spec-validator .
  - cd compliance && QUART_APP=todo:app quart schema | openapi-spec-validator -

pages:
  image: python:3.10
  script:
  - pip install . sphinx pydata-sphinx-theme
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/reference/source/ src/quart_schema/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
